using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SamarPro.Views
{
    public partial class FRM_BOX : Form
    {
        TransationModule TR = new TransationModule();
        void CLEAR_TEXT_BOX(Control CN)
        {
            foreach (Control C in CN.Controls)
                if (C is TextBox)
                    ((TextBox)C).Clear();
                else
                    CLEAR_TEXT_BOX(C);
        }
        public FRM_BOX()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }
        private void bunifuImageButton1_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void btn_new_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            btn_save.Enabled = true;
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            if (txtName.Text == string.Empty || txtNote.Text == string.Empty)
            {
                TR.Show_Message("الرجاء إدخال جميع الحقول");
                return;
            }
            try
            {
                db_model db = new db_model();
                THE_BOX ac = new THE_BOX
                {
                    RES_NAME = combo_Res.Text,
                    PRD_NAME = txtName.Text,
                    NOTE = txtNote.Text,
                    N_DATE = DayDate.Value
                };
                db.Entry(ac).State = System.Data.Entity.EntityState.Added;
                db.SaveChanges();
                TR.Show_Message("تم إضافة شكوى للمنتج");
                sqlDataSource1.Fill();
                btn_save.Enabled = false;
                btn_new.Enabled = true;
                CLEAR_TEXT_BOX(this);
            }
            catch
            {
                return;
            }

        }
    }
}
