using SamarPro.CONTROLS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
using Microsoft.VisualBasic;
using SamarPro.Reports;
using DevExpress.XtraReports.UI;

namespace SamarPro.Views
{
    public partial class frm_Shakawi : Form
    {
        int Shakawi_ID; // for any ID Of Each form 
        CONTROLS.BusneisLayer BL = new CONTROLS.BusneisLayer();
        TransationModule TR = new TransationModule();
        DropShaddow DR = new DropShaddow();
        CONTROLS.DataAccessLayer DAL = new CONTROLS.DataAccessLayer();
        SqlCommand cmd;
        SqlDataReader red;
        int SH_ID;
        void CLEAR_TEXT_BOX(Control CN)
        {
            foreach (Control C in CN.Controls)
                if (C is TextBox)
                    ((TextBox)C).Clear();
                else
                    CLEAR_TEXT_BOX(C);
        }
        public void COM_ID()  // fill combobox from data base
        {
            Com_Emp.DataSource = BL.get_username();
            Com_Emp.DisplayMember = "Name";
            Com_Emp.ValueMember = "ID";
        }
        void get_complimnteID() // this function genrate Id by Increase 1 
        {
            DataTable DT = new DataTable();
            DT = BL.get_complimnteID();
            int id = Convert.ToInt32(DT.Rows[DT.Rows.Count - 1][0]);
            SH_ID = id;           
        }
        void Amal(Boolean SOL)
        {
            btn_del.Enabled = SOL;            
            btn_save.Enabled = SOL;
        }
        int num;
        void get_count()
        {
            DAL.open();
            cmd = new SqlCommand("select count(E_ID) as count from Complaintes where E_ID ='" + Convert.ToInt16(Com_Emp.SelectedValue) + "'", DAL.Sqlconnection);
            red = cmd.ExecuteReader();
            red.Read();

            num =Convert.ToInt32(red["count"]);
            red.Close();
            DAL.close();
        }
        public frm_Shakawi()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void bunifuImageButton1_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void btn_new_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            groupBox1.Enabled = true;
            btn_save.Enabled = true;
            btn_new.Enabled = false;
            btn_del.Enabled = false;
            txtMoney.Text = "0";
            _date.Text = DateTime.Now.ToShortDateString();
            get_complimnteID();
            COM_ID();
        }

        private void frm_Shakawi_Load(object sender, EventArgs e)
        {
           // groupBox1.Enabled = false;
            Amal(false);
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            if (txtname.Text == string.Empty || txtNote.Text == string.Empty)
            {
                TR.Show_Message("الرجاء إدخال جميع الحقول");
                return;
            }
            try
            {   
                db_model db = new db_model();
                Complainte ac = new Complainte
                {                   
                    Name = txtname.Text,
                    Money = Convert.ToDouble(txtMoney.Text),
                    Note = txtNote.Text,
                    E_ID = Convert.ToInt16(Com_Emp.SelectedValue),
                    S_date = _date.Value,
                    SH_ID = SH_ID
                };
                db.Entry(ac).State = System.Data.Entity.EntityState.Added;
                db.SaveChanges();
               
                TR.Show_Message("تم إضافة مخالفة جديدة");
                btn_Print_Click( sender,  e);
                sqlDataSource1.Fill();
                Amal(false);
                btn_save.Enabled = false;
                btn_new.Enabled = true;
                CLEAR_TEXT_BOX(this);
                }
                catch
                {
                TR.Show_Message("تم إضافة مخالفة جديدة");
                }         
            txtMoney.Text = "0";
        }
        private void dgvshakawi_Click(object sender, EventArgs e)
        {
            Com_Emp.Enabled = false;
            btn_del.Enabled = true;
            btn_Print.Enabled = true;
            btn_new.Enabled = true;
            btn_save.Enabled = false;          
            groupBox1.Enabled = true;
            try
            {
                Shakawi_ID = Convert.ToInt32(gridView2.GetFocusedRowCellValue("المعرف"));
                txtname.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("المخالفة"));
                txtNote.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("ملاحظة"));
                txtMoney.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("الخصم"));
                Com_Emp.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("إسم الموظف"));

                string d = Convert.ToString(gridView2.GetFocusedRowCellValue("التاريخ"));
                _date.Value = Convert.ToDateTime(d);
            }
            catch
            {
                return;
            }
        }

        private void txtMoney_KeyPress(object sender, KeyPressEventArgs e)
        {
            DR.JustNumber(e);
        }

        private void txtname_KeyPress(object sender, KeyPressEventArgs e)
        {
            DR.JustString(e);
        }

        private void btn_del_Click(object sender, EventArgs e)
        {
            try
            {
                if (MessageBox.Show("هل تريد حذف المخالفة المحددة؟", "عملية الحذف", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation) == DialogResult.Yes)
                {
                    db_model db = new db_model();
                    Complainte ac = (from c in db.Complaintes where c.ID == Shakawi_ID select c).FirstOrDefault();
                    db.Complaintes.Where(a => a.ID == Shakawi_ID).Select(s => s).FirstOrDefault();
                    db.Entry(ac).State = System.Data.Entity.EntityState.Deleted;
                    db.SaveChanges();
                    
                    TR.EnterLog(": تم حذف المخالفة برقم " + Shakawi_ID);
                    TR.Show_Message("تم حذف المخالفة ");
                }
                else
                {
                    TR.Show_Message("تم إلغاء عملية الحذف");
                }
            }
            catch
            {
                TR.Show_Message("تم حذف المخالفة ");
            }
            CLEAR_TEXT_BOX(this);
            sqlDataSource1.Fill();
            txtMoney.Text = "0";
        }

        private void txtMoney_KeyPress_1(object sender, KeyPressEventArgs e)
        {
            DR.JustNumber(e);
        }
        private void txtname_KeyPress_1(object sender, KeyPressEventArgs e)
        {
            DR.JustString(e);
        }
        private void btn_Print_Click(object sender, EventArgs e)
        {
            get_count();
            Complimnte_Report TK = new Complimnte_Report();
            ReportPrintTool printTool = new ReportPrintTool(TK);
            if (num == 4)
            {
                TR.Show_Message("هذا الإنذار الأخير للموظف  " + Com_Emp.Text);
                this.Cursor = Cursors.WaitCursor;
                TK.Parameters["Complaintes_ID"].Value = SH_ID;
                TK.Parameters["Count_No"].Value = Convert.ToInt32(num);
                printTool.PreviewForm.StartPosition = FormStartPosition.CenterScreen;
                printTool.ShowPreviewDialog();
                this.Cursor = Cursors.Default;
                btn_Print.Enabled = false;
            }
            else if(num > 4)
            {
                TR.Show_Message("عدد المخالفات تعدت الحاجز المسموح " + Com_Emp.Text);
                this.Cursor = Cursors.WaitCursor;
                TK.Parameters["Complaintes_ID"].Value = SH_ID;
                TK.Parameters["Count_No"].Value = Convert.ToInt32(num);
                printTool.PreviewForm.StartPosition = FormStartPosition.CenterScreen;
                printTool.ShowPreviewDialog();
                this.Cursor = Cursors.Default;
                btn_Print.Enabled = false;
            }
            else
            {
                this.Cursor = Cursors.WaitCursor;
                TK.Parameters["Complaintes_ID"].Value = SH_ID;
                TK.Parameters["Count_No"].Value = Convert.ToInt32(num);
                printTool.PreviewForm.StartPosition = FormStartPosition.CenterScreen;
                printTool.ShowPreviewDialog();
                this.Cursor = Cursors.Default;
                btn_Print.Enabled = false;
                CLEAR_TEXT_BOX(this);
            }
        }
        //int E_id;
        private void Com_Emp_SelectedIndexChanged(object sender, EventArgs e)
        {
            //E_id = Convert.ToInt32(Com_Emp.SelectedValue);  
        }
    }
}
