using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SamarPro.Views
{
    public partial class frmformView : Form
    {
        public frmformView()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            sqlDataSource2.Fill();
        }

        private void frmformView_Load(object sender, EventArgs e)
        {
          this.WindowState = FormWindowState.Normal;
        }

        private void dgvShow_Click(object sender, EventArgs e)
        {
            
            Close();        
        }

        private void bunifuImageButton1_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void gridReservation_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void bunifuImageButton2_Click(object sender, EventArgs e)
        {
            sqlDataSource1.Fill();
            sqlDataSource2.Fill();
        }
    }
}
