using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SamarPro.Views
{
    public partial class frmGategory : Form
    {
        int Main_ID,Sub_ID; // for any ID Of Each form 
        TransationModule TR = new TransationModule();
        CONTROLS.BusneisLayer BL = new CONTROLS.BusneisLayer();
        void CLEAR_TEXT_BOX(Control CN)
        {

            foreach (Control C in CN.Controls)
                if (C is TextBox)

                    ((TextBox)C).Clear();

                else

                    CLEAR_TEXT_BOX(C);

        }
        void Amal(Boolean SOL)
        {
            btn_del.Enabled = SOL;
            btn_edit.Enabled = SOL;
            btn_save.Enabled = SOL;

        }
        public frmGategory()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
           //  sqlDataSource1.Fill();
        }

        private void btn_new_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            btn_save.Enabled = true;
            btn_new.Enabled = false;
            btn_del.Enabled = false;
            btn_edit.Enabled = false;
        }

        private void bunifuImageButton1_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void groupBox1_Enter(object sender, EventArgs e)
        {

        }

        private void frmGategory_Load(object sender, EventArgs e)
        {
            groupBox1.Enabled = false;
            Amal(false);
            if (bunifuiOSSwitch1.Value == true)
            {
                splitContainer1.Panel1.Enabled = true;
                splitContainer1.Panel2.Enabled = false;
            }
            else if (bunifuiOSSwitch2.Value == true)
            {

                splitContainer1.Panel2.Enabled = true;
                splitContainer1.Panel1.Enabled = false;
            }
        }

        private void bunifuiOSSwitch1_OnValueChange(object sender, EventArgs e)
        {
            
            // grid_gate.Visible = false;
            if (bunifuiOSSwitch1.Value == true)
            {
                groupBox1.Enabled = true;
                grid_Main.Visible = true;
                splitContainer1.Panel1.Enabled = true;
                splitContainer1.Panel2.Enabled = false;
                bunifuiOSSwitch2.Value = false;
              //  grid_Main.RefreshDataSource();
                grid_Main.DataSource = BL.get_MainGate_data();

            }
            else
            {
                grid_Main.Visible = false;
            }
        }

        private void bunifuiOSSwitch2_OnValueChange(object sender, EventArgs e)
        {
           // grid_Main.Visible = false;
            
            if (bunifuiOSSwitch2.Value == true)
            {
                groupBox1.Enabled = true;
                grid_gate.Visible = true;
                splitContainer1.Panel2.Enabled = true;
                splitContainer1.Panel1.Enabled = false;
                bunifuiOSSwitch1.Value = false;
                comb_Main.DataSource = BL.get_gate_name();
                comb_Main.DisplayMember = "Name";
                comb_Main.ValueMember = "ID";
                grid_gate.RefreshDataSource();
                grid_gate.DataSource = BL.get_supGate_data();
            }
            else
            {
                grid_gate.Visible = false;
            }
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            if (bunifuiOSSwitch1.Value == true)
            {
                db_model db = new db_model();
                ParentCategory sub = new ParentCategory();
                sub.Name = txt_name.Text;
                db.ParentCategorys.Add(sub);
                db.SaveChanges();
                TR.Show_Message("تم إضافة فئة رئيسية");
                grid_Main.DataSource = BL.get_MainGate_data();
                TR.EnterLog(": تم إضافة فئة رئيسية جديدة بأسم " + txt_name.Text);
            }
            else if (bunifuiOSSwitch2.Value == true)
            {
                db_model db = new db_model();
                SupCategory sub = new SupCategory();
                sub.Name = txtName1.Text;
                sub.PAR_id = Convert.ToInt16(comb_Main.SelectedValue);              
                db.SupCategorys.Add(sub);
                db.SaveChanges();
                TR.Show_Message("تم إضافة فئة فرعية");
                grid_gate.DataSource = BL.get_supGate_data();
                TR.EnterLog(": تم إضافة فئة فرعية جديدة بأسم " + txtName1.Text);
            }
            groupBox1.Enabled = false;
            Amal(false);
            btn_save.Enabled = false;
            btn_new.Enabled = true;
            CLEAR_TEXT_BOX(this);
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            if (bunifuiOSSwitch1.Value == true)
            {
                db_model db = new db_model();
                ParentCategory sub = new ParentCategory();
                {
                    sub.Name = txt_name.Text;
                    sub.ID = Main_ID;
                };
                db.Entry(sub).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TR.Show_Message("تم تعديل فئة رئيسية");
                grid_Main.DataSource = BL.get_MainGate_data();
                TR.EnterLog(": تم تعديل فئة رئيسية بأسم " + txt_name.Text);
            }
            else if (bunifuiOSSwitch2.Value == true)
            {
                db_model db = new db_model();
                SupCategory sub = new SupCategory();
                {
                    sub.Name = txtName1.Text;
                    sub.PAR_id = Convert.ToInt32(comb_Main.SelectedValue);
                    sub.ID = Sub_ID;
                };
                db.Entry(sub).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TR.Show_Message("تم تعديل فئة رئيسية");
                grid_gate.DataSource = BL.get_supGate_data();
                TR.EnterLog(": تم تعديل فئة رئيسية بأسم " + txtName1.Text);
            }
            groupBox1.Enabled = false;
            Amal(false);
            btn_edit.Enabled = false;
            btn_new.Enabled = true;
            CLEAR_TEXT_BOX(this);
        }

        private void btn_del_Click(object sender, EventArgs e)
        {
            if (bunifuiOSSwitch1.Value == true)
            {

                if (MessageBox.Show("هل تريد حذف بيانات الفئة المحددة ؟", "عملية الحذف", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation) == DialogResult.Yes)
                {
                    db_model db = new db_model();
                    ParentCategory ac = (from c in db.ParentCategorys where c.ID == Main_ID select c).FirstOrDefault();
                    db.ParentCategorys.Where(a => a.ID == Main_ID).Select(s => s).FirstOrDefault();
                    db.Entry(ac).State = System.Data.Entity.EntityState.Deleted;

                    db.SaveChanges();
                    TR.Show_Message("تم حذف بيانات الفئة ");
                    grid_Main.DataSource = BL.get_MainGate_data();
                    TR.EnterLog(": تم حذف فئة رئيسية بأسم " + txt_name.Text);
                }
                else
                {
                    TR.Show_Message("تم إلغاء عملية الحذف");
                }
                
            }
            else if (bunifuiOSSwitch2.Value == true)
            {
                if (MessageBox.Show("هل تريد حذف بيانات الفئة المحددة ؟", "عملية الحذف", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation) == DialogResult.Yes)
                {
                    db_model db = new db_model();
                    SupCategory ac = (from c in db.SupCategorys where c.ID == Sub_ID select c).FirstOrDefault();
                    db.SupCategorys.Where(a => a.ID == Sub_ID).Select(s => s).FirstOrDefault();
                    db.Entry(ac).State = System.Data.Entity.EntityState.Deleted;

                    db.SaveChanges();
                    TR.Show_Message("تم حذف بيانات الفئة ");
                    grid_gate.DataSource = BL.get_supGate_data();
                    TR.EnterLog(": تم حذف فئة فرعية  بأسم " + txtName1.Text);
                }
                else
                {
                    TR.Show_Message("تم إلغاء عملية الحذف");
                }
                CLEAR_TEXT_BOX(this);
               
            }
        }

        private void grid_gate_Click(object sender, EventArgs e)
        {
            btn_del.Enabled = true;
            btn_new.Enabled = true;
            btn_save.Enabled = false;
            btn_edit.Enabled = true;
            groupBox1.Enabled = true;
            try
            {
               
               if (bunifuiOSSwitch2.Value == true)
                {
                    Sub_ID = Convert.ToInt32(gridView2.GetFocusedRowCellValue("رقم الفئة"));
                    comb_Main.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("الفئة الرئيسية"));
                    txtName1.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("إسم الفئة"));

                }
                
            }
            catch
            {
                return;
            }
        }
        string nme;
        private void txt_name_KeyPress(object sender, KeyPressEventArgs e)
        {
            CONTROLS.DropShaddow dr = new CONTROLS.DropShaddow();
            dr.JustString(e);
        }

        private void txtName1_KeyPress(object sender, KeyPressEventArgs e)
        {
            CONTROLS.DropShaddow dr = new CONTROLS.DropShaddow();
            dr.JustString(e);
        }

        private void grid_Main_Click(object sender, EventArgs e)
        {
            if (bunifuiOSSwitch1.Value == true)
            {
                btn_del.Enabled = true;
                btn_new.Enabled = true;
                btn_save.Enabled = false;
                btn_edit.Enabled = true;
                groupBox1.Enabled = true;
                try
                {

                    Main_ID = Convert.ToInt32(gridView1.GetFocusedRowCellValue("رقم الفئة"));
                    nme = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم الفئة"));
                    txt_name.Text = nme;
                }
                catch
                { return;
                }
            }
        }

        private void splitContainer1_Panel1_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}
