using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using SamarPro.CONTROLS;

namespace SamarPro.Views
{
    public partial class frmResource : Form
    {
        int Resource_ID; // for any ID Of Each form 
        DropShaddow DR = new DropShaddow();
        CONTROLS.BusneisLayer BL = new CONTROLS.BusneisLayer();
        TransationModule TR = new TransationModule();
        void CLEAR_TEXT_BOX(Control CN)
        {

            foreach (Control C in CN.Controls)
                if (C is TextBox)

                    ((TextBox)C).Clear();

                else

                    CLEAR_TEXT_BOX(C);

        }
        void Amal(Boolean SOL)
        {
            btn_del.Enabled = SOL;
            btn_edit.Enabled = SOL;
            btn_save.Enabled = SOL;

        }
        public frmResource()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void bunifuImageButton1_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void btn_new_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            groupBox1.Enabled = true;
            btn_save.Enabled = true;
            btn_new.Enabled = false;
            btn_del.Enabled = false;
            btn_edit.Enabled = false;
        }

        private void groupBox1_Enter(object sender, EventArgs e)
        {

        }

        private void frmBank_Load(object sender, EventArgs e)
        {
            groupBox1.Enabled = false;
            Amal(false);
        }

        private void dgvShow_Click(object sender, EventArgs e)
        {
            btn_del.Enabled = true;
            btn_new.Enabled = true;
            btn_save.Enabled = false;
            btn_edit.Enabled = true;
            groupBox1.Enabled = true;
            try
            {
                Resource_ID = Convert.ToInt32(gridView2.GetFocusedRowCellValue("رقم المورد"));
                txtName.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("إسم المورد"));
                txtNote.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("ملاحظة"));
                txtPhone.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("رقم الهاتف"));
                txtAdd.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("العنوان"));
            }
            catch
            {
                return;
            }
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            // this code for save data in database
            if (txtName.Text == string.Empty || txtPhone.Text == string.Empty)
            {
                TR.Show_Message("الرجاء إدخال جميع الحقول");
                return;
            }
            db_model db = new db_model();
            Resource ac = new Resource
            {
                Note = txtNote.Text,
                Name = txtName.Text,
                Phone = Convert.ToInt32( txtPhone.Text),
                Address = (txtAdd.Text)
            };
            db.Entry(ac).State = System.Data.Entity.EntityState.Added;
            db.SaveChanges();
            sqlDataSource1.Fill();
            TR.Show_Message("تم إضافة مورد جديد");
            groupBox1.Enabled = false;
            Amal(false);
            btn_save.Enabled = false;
            btn_new.Enabled = true;
            CLEAR_TEXT_BOX(this);
            SQL = ": تم إضافة مورد   " + txtName.Text;
            TR.EnterLog(SQL);
        }
        string SQL;
        private void btn_edit_Click(object sender, EventArgs e)
        {
            db_model db = new db_model();
            Resource ac = new Resource
            {
                ID = Resource_ID,
                Note = txtNote.Text,
                Name = txtName.Text,
                Phone = Convert.ToInt32(txtPhone.Text),
                Address = (txtAdd.Text)           
            };
            db.Entry(ac).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            TR.Show_Message("تم تعديل بيانات المورد");
            sqlDataSource1.Fill();
            groupBox1.Enabled = false;
            Amal(false);
            btn_edit.Enabled = false;
            btn_new.Enabled = true;
            CLEAR_TEXT_BOX(this);
            SQL = ": تم تعديل بيانات مورد  برقم  " + Resource_ID;
            TR.EnterLog(SQL);
        }

        private void btn_del_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("هل تريد حذف بيانات المورد المحدد ؟", "عملية الحذف", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation) == DialogResult.Yes)
            {
                db_model db = new db_model();
                Resource ac = (from c in db.Resources where c.ID == Resource_ID select c).FirstOrDefault();
                db.Resources.Where(a => a.ID == Resource_ID).Select(s => s).FirstOrDefault();
                db.Entry(ac).State = System.Data.Entity.EntityState.Deleted;

                db.SaveChanges();
                TR.Show_Message("تم حذف بيانات المورد");
                sqlDataSource1.Fill();
                SQL = ": تم حذف المورد   " + txtName.Text;
                TR.EnterLog(SQL);
            }
            else
            {
                TR.Show_Message("تم إلغاء عملية الحذف");
            }
            CLEAR_TEXT_BOX(this);
            
        }
        
        private void txtAcc_KeyPress(object sender, KeyPressEventArgs e)
        {
            DR.For_Quan(e);
        }

        private void txtBalance_KeyPress(object sender, KeyPressEventArgs e)
        {
            DR.For_Quan(e);
        }

        private void txtName_KeyPress(object sender, KeyPressEventArgs e)
        {
            DR.JustString(e);
        }

        private void txtName_KeyPress_1(object sender, KeyPressEventArgs e)
        {
            DR.JustString(e);
        }

        private void txtAcc_KeyPress_1(object sender, KeyPressEventArgs e)
        {
            DR.JustNumber(e);
        }

        private void txtBalance_KeyPress_1(object sender, KeyPressEventArgs e)
        {
           
        }
    }
}
