using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SamarPro.Views
{
    public partial class frmRent : Form
    {
        int RENT_ID; // for any ID Of Each form 
        TransationModule TR = new TransationModule();
        CONTROLS.BusneisLayer BL = new CONTROLS.BusneisLayer();
        void CLEAR_TEXT_BOX(Control CN)
        {

            foreach (Control C in CN.Controls)
                if (C is TextBox)

                    ((TextBox)C).Clear();

                else

                    CLEAR_TEXT_BOX(C);
        }
        void Amal(Boolean SOL)
        {
            btn_del.Enabled = SOL;
            btn_edit.Enabled = SOL;
            btn_save.Enabled = SOL;
        }
        public frmRent()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        private void bunifuImageButton1_Click(object sender, EventArgs e)
        {
            Close();
        }
        private void btn_new_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            pnl_1.Enabled = true;
            btn_save.Enabled = true;
            btn_new.Enabled = false;
            btn_del.Enabled = false;
            btn_edit.Enabled = false;         
        }
        private void frmRent_Load(object sender, EventArgs e)
        {
            pnl_1.Enabled = false;
            Amal(false);
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            // this code for save data in database
            if (txt_note.Text == string.Empty || txt_type.Text == string.Empty)
            {
                TR.Show_Message("الرجاء إدخال جميع الحقول");
                return;
            }
            db_model db = new db_model();
            Rent ac = new Rent
            {
                Type = txt_type.Text,
                Price = Convert.ToDouble(txt_price.Text),
                Note = txt_note.Text
            };
            db.Entry(ac).State = System.Data.Entity.EntityState.Added;
            db.SaveChanges();
            sqlDataSource1.Fill();
            TR.Show_Message("تم إضافة بيانات إيجار");
            pnl_1.Enabled = false;
            Amal(false);
            btn_save.Enabled = false;
            btn_new.Enabled = true;
            CLEAR_TEXT_BOX(this);
            TR.EnterLog(": تم إضافة بيانات إيجار بإسم " + txt_type.Text);
        }

        private void dgvRent_Click(object sender, EventArgs e)
        {
            btn_del.Enabled = true;
            btn_new.Enabled = true;
            btn_save.Enabled = false;
            btn_edit.Enabled = true;
            pnl_1.Enabled = true;
            try
            {
                RENT_ID = Convert.ToInt32(gridView2.GetFocusedRowCellValue("كود"));
                txt_type.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("نوع الإيجار"));
                txt_note.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("ملاحظة"));
                txt_price.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("السعر"));
            }
            catch
            {
                return;
            }

            }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            db_model db = new db_model();
            Rent ac = new Rent
            {
                ID = RENT_ID,
                Type =  txt_type.Text,
                Price = Convert.ToDouble(txt_price.Text),
                Note = txt_note.Text,           
            };

            db.Entry(ac).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            TR.Show_Message("تم تعديل بيانات إيجار بإسم");
            sqlDataSource1.Fill();
            pnl_1.Enabled = false;
            Amal(false);
            btn_edit.Enabled = false;
            btn_new.Enabled = true;
            CLEAR_TEXT_BOX(this);
            TR.EnterLog(": تم تعديل بيانات إيجار بإسم " + txt_type.Text);
        }

        private void btn_del_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("هل تريد حذف الإيجار المحدد!", "عملية الحذف", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation) == DialogResult.Yes)
            {
                db_model db = new db_model();
                Rent ac = (from c in db.Rents where c.ID == RENT_ID select c).FirstOrDefault();
                db.Rents.Where(a => a.ID == RENT_ID).Select(s => s).FirstOrDefault();
                db.Entry(ac).State = System.Data.Entity.EntityState.Deleted;

                db.SaveChanges();
                TR.Show_Message("تم حذف بيانات إيجار");
                sqlDataSource1.Fill();
                TR.EnterLog(": تم حذف بيانات إيجار بإسم " + txt_type.Text);
            }
            else
            {
                TR.Show_Message("تم إلغاء عملية الحذف");
            }
            CLEAR_TEXT_BOX(this);
        }

        private void txt_price_KeyPress(object sender, KeyPressEventArgs e)
        {
            CONTROLS.DropShaddow dr = new CONTROLS.DropShaddow();
            dr.JustNumber(e);
        }
    }
}
