using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SamarPro.Views
{
    public partial class frmServices : Form
    {
        CONTROLS.DropShaddow dr = new CONTROLS.DropShaddow();
        int Service_ID; // for any ID Of Each form 
        TransationModule TR = new TransationModule();
        CONTROLS.BusneisLayer BL = new CONTROLS.BusneisLayer();
        void CLEAR_TEXT_BOX(Control CN)
        {

            foreach (Control C in CN.Controls)
                if (C is TextBox)

                    ((TextBox)C).Clear();

                else

                    CLEAR_TEXT_BOX(C);
        }
        void Amal(Boolean SOL)
        {
            btn_del.Enabled = SOL;
            btn_edit.Enabled = SOL;
            btn_save.Enabled = SOL;
        }
        void COMBO_PRD()
        {
            comb_type.DataSource = BL.getProduct_Name();
            comb_type.DisplayMember = "Name";
            comb_type.ValueMember = "ID";

            comb_name.DataSource = BL.SELECT_SERVICE();
            comb_name.DisplayMember = "Name";
            comb_name.ValueMember = "ID";
        }
        public frmServices()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            COMBO_PRD();
        }
        private void bunifuImageButton1_Click(object sender, EventArgs e)
        {
            Close();
        }
        private void btn_new_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            groupBox1.Enabled = true;
            btn_save.Enabled = true;
            btn_new.Enabled = false;
            btn_del.Enabled = false;
            btn_edit.Enabled = false;
            COMBO_PRD();
        }
        private void frmServices_Load(object sender, EventArgs e)
        {
            groupBox1.Enabled = false;
            Amal(false);
        }

        private void Grid_Service_Click(object sender, EventArgs e)
        {
            btn_del.Enabled = true;
            btn_new.Enabled = true;
            btn_save.Enabled = false;
            btn_edit.Enabled = true;
            groupBox1.Enabled = true;
            try
            {
                Service_ID = Convert.ToInt32(gridView2.GetFocusedRowCellValue("رقم الخدمة"));
                comb_name.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("إسم الخدمة"));
                txt_price.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("السعر"));
                txt_note.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("ملاحظة"));
                comb_type.Text = Convert.ToString(gridView2.GetFocusedRowCellValue("إسم المنتج"));
            }
            catch
            {
                return;
            }
        }
        private void btn_save_Click(object sender, EventArgs e)
        {
            // this code for save data in database
            if (txt_note.Text == string.Empty || txt_price.Text == string.Empty)
            {
                TR.Show_Message("الرجاء إدخال جميع الحقول");
                return;
            }
            db_model db = new db_model();
            Services ac = new Services
            {
                Note = txt_note.Text,
                Name = comb_name.Text,
                PRD_ID = Convert.ToInt32(comb_type.SelectedValue),
                Money = Convert.ToDouble(txt_price.Text)

            };
            db.Entry(ac).State = System.Data.Entity.EntityState.Added;
            db.SaveChanges();
            sqlDataSource1.Fill();
            TR.Show_Message("تم إضافة بيانات خدمة بإسم");
            groupBox1.Enabled = false;
            Amal(false);
            btn_save.Enabled = false;
            btn_new.Enabled = true;
            CLEAR_TEXT_BOX(this);
            TR.EnterLog(": تم إضافة بيانات خدمة بإسم " + comb_name.Text);
        }

        private void btn_del_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("هل تريد حذف الخدمة المحددة ؟", "عملية الحذف", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation) == DialogResult.Yes)
            {
                db_model db = new db_model();
                Services ac = (from c in db.Services where c.ID == Service_ID select c).FirstOrDefault();
                db.Services.Where(a => a.ID == Service_ID).Select(s => s).FirstOrDefault();
                db.Entry(ac).State = System.Data.Entity.EntityState.Deleted;

                db.SaveChanges();
                TR.Show_Message("تم حذف الخدمة ");
                sqlDataSource1.Fill();
                TR.EnterLog(": تم حذف بيانات خدمة برقم " + Service_ID);
            }
            else
            {
                TR.Show_Message("تم إلغاء عملية الحذف");
            }
            CLEAR_TEXT_BOX(this);
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            db_model db = new db_model();
            Services ac = new Services
            {
                ID = Service_ID,
                Note = txt_note.Text,
                Name = comb_name.Text,
                PRD_ID = Convert.ToInt32(comb_type.SelectedValue),
                Money = Convert.ToDouble(txt_price.Text)

            };
            db.Entry(ac).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            TR.Show_Message("تم تعديل بيانات خدمة");
            sqlDataSource1.Fill();
            groupBox1.Enabled = false;
            Amal(false);
            btn_edit.Enabled = false;
            btn_new.Enabled = true;
            CLEAR_TEXT_BOX(this);
            TR.EnterLog(": تم تعديل بيانات خدمة برقم " + Service_ID);
        }

        private void groupBox1_Enter(object sender, EventArgs e)
        {

        }

        private void txt_price_KeyPress(object sender, KeyPressEventArgs e)
        {
            dr.JustNumber(e);
        }
    }
}
